### ISSUE TITLE
SFV Data

### ISSUE THREAD

**Issue by nathansizemore** [ellipses/Yaksha#30]
Wondering where the SFV data is? Was looking to send a PR to update it and add Gill, but seems it's private and set to whatever server this is running on. Any chance making that a JSON file here that we could submit PRs to?

**Comment by D4RKONION** [comment]
The SFV file is maintained by me

https://github.com/D4RKONION/fatsfvframedatajson

We're currently in the process of updating it, you can read more about it there.
